[build]
builder = "RAILPACK"
buildCommand = "npm run build"
watchPatterns = ["web/**"]

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
